### ISSUE TITLE
Repository contains an example key that end-users should replace

### ISSUE THREAD

**Issue by mex20** [davidstrauss/google-drive-recursive-ownership#24]
I would suggest using a dummy JSON file for the client_secrets.json instead of an actual client. I just followed the directions to run an example execution of this program, and it seems like it is attempting to use a real key. The key had 2FA, so that is good. However a dummy file should be put in it's place.

**Comment by davidstrauss** [comment]
There's no actual private data in the repository. The key file is from [a Google example project](https://github.com/gsuitedevs/python-samples/blob/master/drive/driveapp/client_secrets.json). So, in a sense, it is a dummy file.

There's also no concept of 2FA for the keys, AFAIK. What you're seeing is the OAuth 2.0 flow to authorize the example key to access your account, which is a bad idea.

I'd be happy to take a pull request to update the instructions to tell people to actually obtain and use their own key. Otherwise, they're authorizing the example credentials to access their data.

**Comment by mex20** [comment]
That's great! We can totally close this issue out then.

**Comment by davidstrauss** [comment]
Sounds like a plan!
